In [8]:
import torch
import numpy as np

In [9]:
z = torch.zeros(5, 3)
print(z)
print(z.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [12]:
i = torch.ones((5, 3), dtype=torch.int16)
i

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [13]:
torch.manual_seed(21520378)
r1 = torch.rand(2, 2)
r2 = torch.rand(2, 2)

torch.manual_seed(21520378)
r3 = torch.rand(2, 2)

print(r1)
print(r2)
print(r3)

tensor([[0.4396, 0.3972],
        [0.2207, 0.2099]])
tensor([[0.8677, 0.5851],
        [0.8080, 0.4727]])
tensor([[0.4396, 0.3972],
        [0.2207, 0.2099]])


In [15]:
ones = torch.ones(2, 3)
print(ones)

twos = torch.ones(2, 3) * 2
print(twos)

threes = ones + twos
print(threes)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])


In [16]:
r = torch.rand(2, 2) - 0.5 * 2  # Value between -1 and 1
print(r)

print(torch.abs(r))

print(torch.asin(r))

print(torch.det(r))

print(torch.std_mean(r))
print(torch.max(r))

tensor([[-0.1323, -0.4149],
        [-0.1920, -0.5273]])
tensor([[0.1323, 0.4149],
        [0.1920, 0.5273]])
tensor([[-0.1326, -0.4278],
        [-0.1932, -0.5554]])
tensor(-0.0099)
(tensor(0.1858), tensor(-0.3166))
tensor(-0.1323)
