In [10]:
import torch
import math

# Creating Tensors

In [11]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:
zeros = torch.zeros(4, 4)
ones = torch.ones(4, 4)

torch.manual_seed(21520378)
rands = torch.rand(4, 4)

print(zeros)
print(ones)
print(rands)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.4396, 0.3972, 0.2207, 0.2099],
        [0.8677, 0.5851, 0.8080, 0.4727],
        [0.9289, 0.3781, 0.7688, 0.0934],
        [0.2639, 0.3971, 0.0810, 0.4096]])


# Random Tensors and Seeding

In [13]:
torch.manual_seed(1729)
rands = torch.rand(2, 3)
rands

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])

# Tensor Shapes

In [14]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [15]:
some_constants = torch.tensor([(2, 4, 6), [3, 6, 9]])

In [16]:
some_constants

tensor([[2, 4, 6],
        [3, 6, 9]])

*torch.tensor() creates a copy of the data*

# Tensor Data Type

In [17]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20
print(b)

c = b.to(torch.int32)
print(c)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[17.3151, 14.5980,  6.0404],
        [18.0429,  7.2532, 19.6519]], dtype=torch.float64)
tensor([[17, 14,  6],
        [18,  7, 19]], dtype=torch.int32)
tensor([[17.3151, 14.5980,  6.0404],
        [18.0429,  7.2532, 19.6519]], dtype=torch.float64)


- bool
- int8
- uint8
- int16
- int32
- int64
- half
- float
- double
- bfloat

# Math & Logic with Pytorch Tensors

## Broadcasting

In [18]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3, 2)  # dim 1 absent

c = a * torch.rand(3, 1)  # dim 2 identical to a, dim 3 = 1

d = a * torch.rand(1, 2)  # dim 3 identical to a, dim 2 = 1

e = a * torch.rand(1, 3)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2

In [ ]:
a = torch.tensor(5)
print(a)
print(a.shape)

b = torch.tensor((5, ))
print(b)
print(b.shape)

In [ ]:
torch.rand((0, )).shape

In [ ]:
a.matmul_(b)

In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 4)

print(a)
print(a.matmul(b))
print(a)

# Moving to GPU

In [ ]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    print('Sorry, CPU only.')

In [ ]:
if torch.cuda.is_available():
    gpu_rand = torch.rand(2, 2, device='cuda')
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

In [ ]:
import time

In [ ]:
my_device = torch.device('cpu')

In [ ]:
y = gpu_rand.to(my_device)
y

In [ ]:
gpu_rand

In [ ]:
t1 = time.time()
x = torch.zeros(10000, 1000)
t2 = time.time()

print(t2 - t1)

t1 = time.time()
y = torch.zeros(10000, 1000, device='cuda')
t2 = time.time()

print(t2 - t1)

In [ ]:
torch.cuda.device_count()

# Manipulating Tensor Shapes

## Changing the Number of Dimensions

In [ ]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

In [ ]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

In [ ]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

In [ ]:
b.shape[0]

In [ ]:
a.shape[0]

In [ ]:
a = torch.rand(20, 1)
b = a.squeeze(1)

print(a.shape)
print(b.shape)

In [25]:
a = torch.ones(4, 3, 2)
b = torch.rand(      3)
c = b.unsqueeze(1)

print(c.shape)
print(a * c)

torch.Size([3, 1])
tensor([[[0.1379, 0.1379],
         [0.2318, 0.2318],
         [0.0231, 0.0231]],

        [[0.1379, 0.1379],
         [0.2318, 0.2318],
         [0.0231, 0.0231]],

        [[0.1379, 0.1379],
         [0.2318, 0.2318],
         [0.0231, 0.0231]],

        [[0.1379, 0.1379],
         [0.2318, 0.2318],
         [0.0231, 0.0231]]])


In [29]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

torch.Size([6, 20, 20])
torch.Size([2400])


## Numpy Bridge

In [30]:
import numpy as np

In [32]:
np_array = np.ones((2, 3))
print(np_array)

pytorch_tensor = torch.from_numpy(np_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [33]:
np_array = pytorch_tensor.numpy()
print(np_array)

[[1. 1. 1.]
 [1. 1. 1.]]
